config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]

  resources :tenancies
  resources :tenants
  resources :properties
  root "home#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"
end

app/models/tenant.rb
class Tenant < ApplicationRecord
    belongs_to :property, :optional => true
    belongs_to :tenancy, :optional => true
    belongs_to :user, :optional => true
end

app/controllers/tenants_controller.rb
class TenantsController < ApplicationController
  before_action :set_tenant, only: %i[ show edit update destroy ]
  before_action :check_for_login
  # GET /tenants or /tenants.json
  def index
    # @tenants = Tenant.all
    @tenants = Current.user.tenants
  end

  # GET /tenants/1 or /tenants/1.json
  def show
  end

  # GET /tenants/new
  def new
    @tenant = Tenant.new
    
  end

  # GET /tenants/1/edit
  def edit
  end

  # POST /tenants or /tenants.json
  def create
    @tenant = Tenant.new(tenant_params)
    Current.user.tenants << @tenant

    respond_to do |format|
      if @tenant.save
        format.html { redirect_to tenant_url(@tenant), notice: "Tenant was successfully created." }
        format.json { render :show, status: :created, location: @tenant }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenants/1 or /tenants/1.json
  def update
    respond_to do |format|
      if @tenant.update(tenant_params)
        format.html { redirect_to tenant_url(@tenant), notice: "Tenant was successfully updated." }
        format.json { render :show, status: :ok, location: @tenant }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tenant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenants/1 or /tenants/1.json
  def destroy
    @tenant.destroy

    respond_to do |format|
      format.html { redirect_to tenants_url, notice: "Tenant was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenant
      @tenant = Tenant.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tenant_params
      params.require(:tenant).permit(:first_name, :last_name, :email_address, :phone_number, :property_id, :tenancy_id, :user_id)
    end
end

app/helpers/tenants_helper.rb
module TenantsHelper
end

app/views/tenants/_form.html.erb
<%= form_with(model: tenant) do |form| %>
  <% if tenant.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tenant.errors.count, "error") %> prohibited this tenant from being saved:</h2>

      <ul>
        <% tenant.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name, class:"form-control" %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name, class:"form-control" %>
  </div>

  <div>
    <%= form.label :email_address, style: "display: block" %>
    <%= form.text_field :email_address, class:"form-control" %>
  </div>

  <div>
    <%= form.label :phone_number, style: "display: block" %>
    <%= form.text_field :phone_number, class:"form-control" %>
  </div>

  <div>
    <%= form.label :property_id, style: "display: block" %>
    <%= form.select :property_id, Current.user.properties.pluck(:street_address, :id), :include_blank => true, class:"form-control" %>
  </div>

  <div>
    <%= form.label :tenancy, style: "display: block" %>
    <%= form.select :tenancy_id, Current.user.tenancies.pluck(:name, :id), :include_blank => true, class:"form-control" %>
  </div>

  <div>
    <%= form.submit :Submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/tenants/_tenant.html.erb
<div id="<%= dom_id tenant %>">
  <p>
    <strong>First name:</strong>
    <%= tenant.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= tenant.last_name %>
  </p>

  <p>
    <strong>Email address:</strong>
    <%= tenant.email_address %>
  </p>

  <p>
    <strong>Phone number:</strong>
    <%= tenant.phone_number %>
  </p>

  <p>
    <strong>Property:</strong>
    <%= tenant.property_id %>
  </p>

  <p>
    <strong>Tenancy:</strong>
    <%= tenant.tenancy_id %>
  </p>

</div>

app/views/tenants/edit.html.erb
<h1>Editing tenant</h1>

<%= render "form", tenant: @tenant %>

<br>

<div>
  <%= link_to "Show this tenant", @tenant %> |
  <%= link_to "Back to tenants", tenants_path %>
</div>

app/views/tenants/index.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<h1>Tenants</h1>

<%= link_to "Create new tenant", new_tenant_path, class:"btn btn-outline-success" %>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">First Name</th>
      <th scope="col">Last Name</th>
      <th scope="col">Email</th>
      <th scope="col">Phone Number</th>
      <th scope="col">Associated Rental</th>
      <th scope="col">Tenancy Details</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @tenants.each do |tenant| %>
    <tr>
      <td><%= tenant.first_name %></td>
      <td><%= tenant.last_name %></td>
      <td><%= tenant.email_address %></td>
      <td><%= tenant.phone_number %></td>

      <% if tenant.property.present? %>
        <td><%= link_to tenant.property.street_address, tenant.property %></td>
      <% else %>
        <td></td>
      <% end %>

      <% if tenant.tenancy.present? %>
        <td><%= link_to tenant.tenancy.name, tenant.tenancy %></td>
      <% else %>
        <td></td>
      <% end %>

      <td><%= link_to "Edit", edit_tenant_path(tenant), class:"btn btn-primary" %></td>
      <td><%= button_to "Delete", tenant, method: :delete, class:"btn btn-outline-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tenants/new.html.erb
<h1>New tenant</h1>

<%= render "form", tenant: @tenant %>

<br>

<div>
  <%= link_to "Back to tenants", tenants_path, class:"btn btn-outline-dark" %>
</div>

app/views/tenants/show.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<h1>Tenant Record</h1>

<%= render @tenant %>

<%# <%= link_to @tenant.property.street_address, @tenant.property %>

<div>
  <%= link_to "Edit this tenant", edit_tenant_path(@tenant), class:"btn btn-secondary" %>
  <%= link_to "Back to tenants", tenants_path, class:"btn btn-secondary" %>

  <%= button_to "Delete", @tenant, method: :delete, class:"btn btn-outline-danger" %>
</div>