config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]

  resources :tenancies
  resources :tenants
  resources :properties
  root "home#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"
end

app/models/tenancy.rb
class Tenancy < ApplicationRecord
    has_many :tenants
    belongs_to :user, :optional => true
end

app/controllers/tenancies_controller.rb
class TenanciesController < ApplicationController
  before_action :check_for_login
  before_action :set_tenancy, only: %i[ show edit update destroy ]

  # GET /tenancies or /tenancies.json
  def index
    # @tenancies = Tenancy.all
    @tenancies = Current.user.tenancies.includes(:tenants)
  end

  # GET /tenancies/1 or /tenancies/1.json
  def show
  end

  # GET /tenancies/new
  def new
    @tenancy = Tenancy.new
  end

  # GET /tenancies/1/edit
  def edit
  end

  # POST /tenancies or /tenancies.json
  def create
    @tenancy = Tenancy.new(tenancy_params)
    Current.user.tenancies << @tenancy

    respond_to do |format|
      if @tenancy.save
        format.html { redirect_to tenancy_url(@tenancy), notice: "Tenancy was successfully created." }
        format.json { render :show, status: :created, location: @tenancy }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tenancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tenancies/1 or /tenancies/1.json
  def update
    respond_to do |format|
      if @tenancy.update(tenancy_params)
        format.html { redirect_to tenancy_url(@tenancy), notice: "Tenancy was successfully updated." }
        format.json { render :show, status: :ok, location: @tenancy }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tenancy.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tenancies/1 or /tenancies/1.json
  def destroy
    @tenancy.destroy

    respond_to do |format|
      format.html { redirect_to tenancies_url, notice: "Tenancy was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tenancy
      @tenancy = Tenancy.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tenancy_params
      params.require(:tenancy).permit(:start_date, :end_date, :contractual_basis, :has_pets, :bond_amount, :pays_water, :pays_gas, :pays_electricity, :weekly_rent, :user_id, :name)
    end
end

app/helpers/tenancies_helper.rb
module TenanciesHelper
end

app/views/tenancies/_form.html.erb
<%= form_with(model: tenancy) do |form| %>
  <% if tenancy.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tenancy.errors.count, "error") %> prohibited this tenancy from being saved:</h2>

      <ul>
        <% tenancy.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label "Agreement Name", style: "display: block" %>
    <%= form.text_field :name, class:"form-control" %>
  </div>

  <div>
    <%= form.label :start_date, style: "display: block" %>
    <%= form.text_field :start_date, :placeholder => 'YYYY-MM-DD', class:"form-control" %>
  </div>

  <div>
    <%= form.label :end_date, style: "display: block" %>
    <%= form.text_field :end_date, :placeholder => 'YYYY-MM-DD', class:"form-control" %>
  </div>

<!--
  <div>
    <%= form.label :contractual_basis, style: "display: block" %>
    <%= form.select :contractual_basis, ['Annual', '6-monthly', 'Month-to-month'], :include_blank => true  %>
  </div>
-->

  <div>
    <%= form.label :contractual_basis, style: "display: block" %>
    <%= form.select :contractual_basis, options_for_select([
      ["Select One", ""], 
      "Annual", 
      "6-monthly", 
      "Month to Month"]), 
      {}, { class: "form form-group form-control" } %>
  </div>

  <div>
    <%= form.label :has_pets, style: "display: block" %>
    <%= form.check_box :has_pets %>
  </div>

<!-- >
  <div>
    <%= form.label :bond_amount, style: "display: block" %>
    <%= form.number_field :bond_amount, class:"form-control" %>
  </div>
  -->
  <div>
    <%= form.label :bond_amount, style: "display: block", class:"form-label" %>

    <div class="input-group mb-3">
    <span class="input-group-text">$</span>

    <%= form.number_field :bond_amount, class:"form-control" %>
    </div>
  </div>

  <div>
    <%= form.label :pays_water, style: "display: block" %>
    <%= form.select :pays_water, options_for_select([
      ["Select One", ""], 
      "Owner", 
      "Tenant"]), 
      {}, { class: "form form-group form-control" } %>
  </div>

  <div>
    <%= form.label :pays_gas, style: "display: block" %>
    <%= form.select :pays_gas, options_for_select([
      ["Select One", ""], 
      "Owner", 
      "Tenant"]), 
      {}, { class: "form form-group form-control" } %>
  </div>

  <div>
    <%= form.label :pays_electricity, style: "display: block" %>
    <%= form.select :pays_electricity, options_for_select([
      ["Select One", ""], 
      "Owner", 
      "Tenant"]), 
      {}, { class: "form form-group form-control" } %>
  </div>
  
<!-- >
  <div>
    <%= form.label :weekly_rent, style: "display: block" %>
    <%= form.number_field :weekly_rent %>
  </div>
-->

  <div>
    <%= form.label :weekly_rent, style: "display: block", class:"form-label" %>

    <div class="input-group mb-3">
    <span class="input-group-text">$</span>

    <%= form.number_field :weekly_rent, class:"form-control" %>
    </div>
  </div>

  <div>
    <%= form.submit :Submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/tenancies/_tenancy.html.erb
<div id="<%= dom_id tenancy %>">

  <p>
    <strong>Agreement Name:</strong>
    <%= tenancy.name %>
  </p>

  <p>
    <strong>Start date:</strong>
    <%= tenancy.start_date.strftime '%B %e, %Y' unless tenancy.start_date.nil? %>
  </p>

  <p>
    <strong>End date:</strong>
    <%= tenancy.end_date.strftime '%B %e, %Y' unless tenancy.end_date.nil? %>
  </p>

  <p>
    <strong>Contractual basis:</strong>
    <%= tenancy.contractual_basis %>
  </p>

  <p>
    <strong>Has pets:</strong>
    <%= tenancy.has_pets %>
  </p>

  <p>
    <strong>Bond amount:</strong>
    $<%= tenancy.bond_amount %>
  </p>

  <p>
    <strong>Pays water:</strong>
    <%= tenancy.pays_water %>
  </p>

  <p>
    <strong>Pays gas:</strong>
    <%= tenancy.pays_gas %>
  </p>

  <p>
    <strong>Pays electricity:</strong>
    <%= tenancy.pays_electricity %>
  </p>

  <p>
    <strong>Weekly rent:</strong>
    <%= tenancy.weekly_rent %>
  </p>

  <p>
    <strong>Tenant:</strong>
    <% tenancy.tenants.each do |t| %>
    <%= t.first_name %>
    <% end %>
  </p>

</div>

app/views/tenancies/edit.html.erb
<h1>Editing tenancy</h1>

<%= render "form", tenancy: @tenancy %>

<br>

<div>
  <%= link_to "Show this tenancy", @tenancy %> |
  <%= link_to "Back to tenancies", tenancies_path %>
</div>

app/views/tenancies/index.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<h1>Tenancies</h1>

<%= link_to "Create new tenancy", new_tenancy_path, class:"btn btn-outline-success"  %>

<table class="table table-striped">
  <thead>
    <tr>
      <th scope="col">Agreement Name</th>
      <th scope="col">Start Date</th>
      <th scope="col">End Date</th>
      <th scope="col">Contractual Basis</th>
      <th scope="col">Pets?</th>
      <th scope="col">Bond Amount</th>
      <th scope="col">Pays water</th>
      <th scope="col">Pays gas</th>
      <th scope="col">Pays electricity</th>
      <th scope="col">Tenant</th>
      <th scope="col"></th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
    <% @tenancies.each do |tenancy| %>
    <tr>
      <td><%= tenancy.name %></td>
      <td><%= tenancy.start_date %></td>
      <td><%= tenancy.end_date %></td>
      <td><%= tenancy.contractual_basis %></td>
      <td><%= tenancy.has_pets %></td>
      <td><%= tenancy.bond_amount %></td>
      <td><%= tenancy.pays_water %></td>
      <td><%= tenancy.pays_gas %></td>
      <td><%= tenancy.pays_electricity %></td>
      
      <td>
        <% tenancy.tenants.each do |t| %>
        <%= t.first_name %>
        <% end %>
      </td>
      
      <td><%= link_to "Edit", edit_tenancy_path(tenancy), class:"btn btn-primary" %></td>
      <td><%= button_to "Delete", tenancy, method: :delete, class:"btn btn-outline-danger" %></td>
    </tr>
    <% end %>
  </tbody>
</table>

app/views/tenancies/new.html.erb
<h1>New tenancy</h1>

<%= render "form", tenancy: @tenancy %>

<br>

<div>
  <%= link_to "< Back to tenancies", tenancies_path, class:"btn btn-outline-dark" %>
</div>

app/views/tenancies/show.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<h1>Tenancy Record</h1>

<%= render @tenancy %>

<div>
  <%= link_to "Edit this tenancy", edit_tenancy_path(@tenancy), class:"btn btn-secondary" %>
  <%= link_to "Back to tenancies", tenancies_path, class:"btn btn-secondary" %>

  <%= button_to "Delete", @tenancy, method: :delete, class:"btn btn-outline-danger" %>
</div>