config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]

  resources :tenancies
  resources :tenants
  resources :properties
  root "home#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"
end

app/models/property.rb
class Property < ApplicationRecord
    belongs_to :user
    has_many :tenants

    def address
        [street_address, suburb, country].compact.join(', ')
    end

    geocoded_by :address
    after_validation :geocode
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]
  before_action :check_for_login

  # GET /properties or /properties.json
  def index
    # @properties = Property.all
    @properties = Current.user.properties
  end

  # GET /properties/1 or /properties/1.json
  def show
    # @property = Property.joins(:tenants).where(tenants:{property_id: params[:id]}).take
  end

  # GET /properties/new
  def new
    @property = Property.new
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = Property.new(property_params)
    Current.user.properties << @property

    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:street_address, :property_type, :user_id, :postcode, :state, :country, :lot_size, :suburb, :bedrooms, :bathrooms, :carspaces, :image, :latitude, :longitude)
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property, class:"form") do |form| %>
  <% if property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :street_address, style: "display: block", class: "form-label" %>
    <%= form.text_field :street_address, class:"form-control" %>
  </div>

  <div>
    <%= form.label :suburb, style: "display: block", class:"form-label" %>
    <%= form.text_field :suburb, class:"form-control" %>
  </div>

  <div>
    <%= form.label :property_type, style: "display: block", class:"form-label" %>
    <%= form.text_field :property_type, class:"form-control" %>
  </div>

<!--
  <div>
    <%= form.label :user_id, style: "display: block", class:"form-label" %>
    <%= form.number_field :user_id %>
  </div>
-->

  <div>
    <%= form.label :postcode, style: "display: block", class:"form-label" %>
    <%= form.number_field :postcode, class:"form-control" %>
  </div>

<!-- 
  <div>
    <%= form.label :state, style: "display: block", class:"form-label" %>
    <%= form.text_field :state, class:"form-control" %>
  </div>
-->

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.select :state, options_for_select([
      ["Select One", ""], 
      "NSW", 
      "QLD", 
      "VIC", 
      "SA", 
      "WA"]), 
      {}, { class: "form form-group form-control" } %>
  </div>

  <div>
    <%= form.label :country, style: "display: block", class:"form-label" %>
    <%= form.text_field :country, class:"form-control" %>
  </div>

  <div>
    <%= form.label :lot_size, style: "display: block", class:"form-label" %>

    <div class="input-group mb-3">
    <span class="input-group-text">sq. metres</span>

    <%= form.number_field :lot_size, class:"form-control" %>
    </div>
  </div>


  <div>
    <%= form.label :bedrooms, style: "display: block", class:"form-label" %>
    <%= form.number_field :bedrooms, class:"form-control" %>
  </div>

  <div>
    <%= form.label :bathrooms, style: "display: block", class:"form-label" %>
    <%= form.number_field :bathrooms, class:"form-control" %>
  </div>

  <div>
    <%= form.label :carspaces, style: "display: block", class:"form-label" %>
    <%= form.number_field :carspaces, class:"form-control" %>
  </div>

  <div>
    <%= form.label :image, style: "display: block", class:"form-label" %>
    <%= form.text_field :image, class:"form-control" %>
  </div>

  <div>
    <%= form.submit :Submit, class: 'btn btn-success' %>
  </div>
<% end %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">

  <p>
    <strong>Property type:</strong>
    <%= property.property_type %>
  </p>

  <p>
    <strong>Street address:</strong>
    <%= property.street_address %>
  </p>

  <p>
    <strong>Suburb</strong>
    <%= property.suburb %>
  </p>

  <p>
    <strong>Postcode:</strong>
    <%= property.postcode %>
  </p>

  <p>
    <strong>State:</strong>
    <%= property.state %>
  </p>

  <p>
    <strong>Country:</strong>
    <%= property.country %>
  </p>

  <p>
    <strong>Lot size:</strong>
    <%= property.lot_size %>
  </p>

  <p>
    <strong>Bedrooms:</strong>
    <%= property.bedrooms %>
  </p>

  <p>
    <strong>Bathrooms:</strong>
    <%= property.bathrooms %>
  </p>

  <p>
    <strong>Carspaces:</strong>
    <%= property.carspaces %>
  </p>

<!-- Keep URL hidden after form
  <p>
    <strong>Image:</strong>
    <%= property.image %>
  </p>
<---->


</div>

app/views/properties/edit.html.erb
<h1>Edit property details</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "< Back", @property, class:"btn btn-outline-dark"  %>
  <%= link_to "Back to properties", properties_path, class:"btn btn-outline-dark"  %>
</div>

app/views/properties/index.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<h1>Properties</h1>
<%= link_to "Add new property", new_property_path, class:"btn btn-outline-success" %>


<div class="row">
<% @properties.each do |property| %>
  <div class="col-sm-6">
    <div class="card">
      <img src="<%= property.image %>" class="card-img-top;" alt="...">

      <div class="card-body">
        <h5 class="card-title"><%= property.street_address %></h5>
        <p class="card-text text-secondary"><%= property.suburb %>, <%= property.state %> <%= property.postcode %></p>

        <%= link_to "See more", property, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
  <% end %>
</div>

app/views/properties/new.html.erb
<h1>Add New Property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "< Back to properties", properties_path, class:"btn btn-outline-dark" %>
</div>

app/views/properties/show.html.erb
<% if notice.present? %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>

<h1> Record: 
  <%= @property.street_address %>, <%= @property.suburb %>
</h1>

<%= render @property %>

<iframe
  width="600"
  height="450"
  style="border:0"
  loading="lazy"
  allowfullscreen
  referrerpolicy="no-referrer-when-downgrade"
  src="https://www.google.com/maps/embed/v1/streetview?key=<%=ENV["MAPS_API_KEY"]%>&location=<%=@property.latitude%>,<%=@property.longitude%>&heading=210&pitch=10&fov=35">
</iframe>

<div>
  <%= link_to "Edit this property", edit_property_path(@property), class:"btn btn-secondary" %>
  <%= link_to "Back to properties", properties_path, class:"btn btn-secondary" %>

  <%= button_to "Delete", @property, method: :delete, :data => { :confirm => 'Are you sure?' }, class:"btn btn-outline-danger" %>
</div>