config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create]

  resources :tenancies
  resources :tenants
  resources :properties
  root "home#index"

  get "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"

  get "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"

  delete "logout", to: "sessions#destroy"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "PropertyLink", root_path, class:"navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <ul class="navbar-nav me-auto mb-2 mb-lg-0">

        <li class="nav-item">
            <%= link_to "Properties", properties_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
            <%= link_to "Tenants", tenants_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
            <%= link_to "Tenancies", tenancies_path, class:"nav-link" %>
        </li>

      </ul>

      
    <div class="navbar-nav" ms-auto mb-2 mb-lg-0 >
      <% if Current.user %>
        <li class="nav-item">
          <span class="navbar-text"><%= Current.user.email %></span>
        </li>

        <li class="nav-item">
          <%= button_to "Logout", logout_path, method: :delete, class: "btn btn-outline-primary" %>
        </li>

      <% else %>
      <li class="nav-item">
        <%= link_to "Sign Up", sign_up_path, class: "nav-link" %>
      </li>
        
      <li class="nav-item">
        <%= link_to "Login", sign_in_path, class: "nav-link" %>
      </li>

      <% end %>
    </div>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Us</h1>

app/views/home/index.html.erb
<div class="d-flex align-items-center justify-content-center">
    <h1>Welcome</h1>
</div>

  <% if notice %>
    <div class="alert alert-primary"><%= notice %></div>
  <% end %>

  <% if alert %>
    <div class="alert alert-warning"><%= alert %></div>
  <% end %>